M48
; DRILL file {KiCad (6.0.7-1)-1} date Monday, August 08, 2022 at 08:02:01 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-08T08:02:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X4.85Y-4.19
X4.85Y-4.31
X4.97Y-4.43
X7.41Y-4.26
X7.42Y-4.38
T0
M30
