M48
; DRILL file {KiCad (6.0.7-1)-1} date Friday, August 05, 2022 at 01:03:51 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-05T13:03:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X4.97Y-4.19
X4.97Y-4.31
X4.97Y-4.43
X7.47Y-4.31
X7.47Y-4.43
T0
M30
